config/routes.rb
Store::Application.routes.draw do
  root to: 'products#index'
  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}
  resources :products
  resources :searches do
    member do
      put :toggle_notification
    end
    collection  do
      get :notify_new_results
    end
  end
  
  match "/nt" => 'searches#notify_new_results'
end

app/models/search.rb
# == Schema Information
#
# Table name: searches
#
#  id                              :integer          not null, primary key
#  keywords                        :string(255)
#  category_id                     :integer
#  min_price                       :decimal(, )
#  max_price                       :decimal(, )
#  created_at                      :datetime         not null
#  updated_at                      :datetime         not null
#  user_id                         :integer          not null
#  saved                           :boolean          default(FALSE), not null
#  notify                          :boolean          default(FALSE), not null
#  notified_at                     :datetime
#  new_results_presence            :boolean          default(FALSE)
#  new_results_presence_checked_at :datetime
#

class Search < ActiveRecord::Base
  
  belongs_to :user
  
  # Asyncnchronously handled class methods
  class << self
    def check_new_results_presence
      searches = Search.where(notify: true).where(new_results_presence: false).order(:new_results_presence_checked_at).limit(CONFIG[:number_of_searches_to_be_checked_for_new_results])
      searches.each {|s| s.find_new_results}
    end
    handle_asynchronously :check_new_results_presence, queue: 'searches-check-new-results-presence', priority: 5

    def notify_new_results_by_mail
      # fetch users to be notified    
      searches = Search.select('DISTINCT searches.user_id, searches.notified_at').where(new_results_presence: true).order(:notified_at).limit(CONFIG[:max_daily_emails])
      # notify users 
      searches.each {|s| SearchNotifier.delay(queue: 'searches-newsletters-delivering', priority: 1).new_search_results_for(s.user)}
    end
    handle_asynchronously :notify_new_results_by_mail, queue: 'searches-newsletters-processing', priority: 0

    def clear_unsaved
      Search.where(saved: false).where('updated_at < ?', Time.now - CONFIG[:search_life_in_days].days).destroy_all
    end
    handle_asynchronously :clear_unsaved, queue: 'searches-clear-unsaved', priority: 10 
  end
                                                               
  # TODO
  # If a search is to be notified, then it should aslo be saved
  # If a search is deleted from preferred ones, than it cannot be notified anymore
  
  def products
    @products ||= find_products
  end 
  
  # to check if there are new results (since last notification) to be notified by email
  def new_results
    @new_results ||= find_new_results
  end  
  
  # called from views to show recent new results 
  def recent_new_results
    @recent_new_results ||= find_recent_new_results
  end
  
  def toggle_notify!
    self.notify = !self.notify
    self.saved  = true if self.notify
    self.save!
  end 

  
private

  def find_products
    products = Product.order(:name)
    products = products.where("name like ?", "%#{keywords}%") if keywords.present?
    products = products.where(category_id: category_id) if category_id.present?
    products = products.where("price >= ?", min_price) if min_price.present?
    products = products.where("price <= ?", max_price) if max_price.present?
    products
  end  
  
  def find_new_results
    # If a search has never been notified before, since notified_at is nil, 
    # the time_reference is the search updated_at attribute. 
    time_reference = self.notified_at ? self.notified_at : self.updated_at
    new_result_products = products.where("updated_at >= ?", time_reference)
    self.update_attributes(new_results_presence: new_result_products.any?, new_results_presence_checked_at: Time.now) 
    return new_result_products
  end 
  
  def find_recent_new_results
    products.where("updated_at >= ?", Time.now - 30.days).order('updated_at DESC')
  end  
  
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  
  # user needs to login before perform advanced searches 
  # TODO before_filter to ensure current_user can CRUD only his own searches
  before_filter :authenticate_user!
  
  def new
    @search = current_user.searches.new
  end
  
  def create
    @search = current_user.searches.create!(params[:search])
    redirect_to @search
  end
  
  def show
    @search = Search.find(params[:id])
  end 
  
  def index
    @searches = current_user.searches 
  end  
  
  def edit
    @search = Search.find(params[:id])
  end 
  
  def update
    @search = Search.find(params[:id])
    @search.notified_at = nil # an updated search has never been notified before
    if @search.update_attributes(params[:search])
        flash[:notice] = "Search updated"
        redirect_to searches_path 
     else
       render action: "edit" 
    end
  end 
  
  def toggle_notification
    @search = Search.find(params[:id])
    @search.toggle_notify!
    notice = "Mail notification #{@search.notify ? 'activated' : 'deactivated'}."
    respond_to do |format|
      format.html { flash[:notice] = notice; redirect_to searches_path }
      format.js   { flash.now[:notice] = notice }
    end
  end
  
  def destroy
    @search = Search.find(params[:id])  
    @search.destroy     
    flash[:notice] = "Search destroyed."
    redirect_to searches_path
  end
  
  def notify_new_results
    SearchNotifier.delay(queue: 'users-preferred-searches-new-results-newsletter').new_search_results_for(current_user)
    redirect_to root_path
  end
  
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/searches/_form.html.erb
<%= form_for @search do |f| %>
  <div class="field">
    <%= f.label :keywords %><br />
    <%= f.text_field :keywords %>
  </div>
  <div class="field">
    <%= f.label :category_id %><br />
    <%= f.collection_select :category_id, Category.order(:name), :id, :name, include_blank: true %>
  </div>
  <div class="field">
    <%= f.label :min_price, "Price Range" %><br />
    <%= f.text_field :min_price, size: 10 %> -
    <%= f.text_field :max_price, size: 10 %>
  </div>
  <div class="actions"><%= f.submit "Search" %></div>
<% end %>

app/views/searches/_search.html.erb
<tr class="user-search">
<td><%= search.keywords -%></td>
<td><%= Category.find(search.category_id).name -%></td>
<td><%= search.min_price -%> - <%= search.max_price -%></td>
<td><%= link_to search.products.count, search_path(search) -%></td>
<td id="notify-toggle-<%=search.id%>"> <%= link_to (search.notify ? "ON" : "OFF"), toggle_notification_search_path(search),
    title: 'Click to toggle mail notification.', remote: true, method: :put %>
</td>
<td><%= search.notified_at ? search.notified_at : "none yet" -%></td>
<td><%= search.new_results.count -%></td>
<td>
  <%= link_to "edit", edit_search_path(search) -%>
  <%= link_to "destroy", search_path(search), :method => :delete, :confirm => 'Are you sure?'-%>
</td>
<tr>

app/views/searches/edit.html.erb
<h1>Edit Search</h1>

<%= render partial: 'form' %>

app/views/searches/index.html.erb
<h1>Your preferred searches</h1>

<table border="0" cellspacing="5" cellpadding="5">
  <thead>
    <tr>
     <th>keywords</th>
     <th>category</th>
     <th>price-range</th> 
     <th>results</th>
     <th>mail notification</th>
     <th>last notification</th>
     <th>new results</th>
     <th>controls</th>
    </tr>
  </thead>
  <tbody>
    <%= render @searches -%>
  <tbody>  
</table>

app/views/searches/new.html.erb
<h1>Advanced Search</h1>

<%= render partial: 'form' %>

app/views/searches/show.html.erb
<h1>Search Results</h1>

<%= render @search.products %>

app/views/searches/toggle_notification.js.erb
$("#flash-messages").html('<%= j render :partial => "layouts/flash", :locals => {:flash => flash} -%>')
$("#notify-toggle-<%=@search.id-%> a").html('<%= @search.notify ? "ON" : "OFF"-%>');