config/routes.rb
Store::Application.routes.draw do
  root to: 'products#index'
  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}
  resources :products
  resources :searches do
    member do
      put :toggle_notification
    end
    collection  do
      get :notify_new_results
    end
  end
  
  match "/nt" => 'searches#notify_new_results'
end

app/models/product.rb
# == Schema Information
#
# Table name: products
#
#  id          :integer          not null, primary key
#  name        :string(255)
#  category_id :integer
#  price       :decimal(, )
#  released_at :date
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Product < ActiveRecord::Base
  belongs_to :category

  def self.search(keywords)
    products = order(:name)
    products = products.where("name like ?", "%#{keywords}%") if keywords.present?
    products
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.search(params[:search])
  end

  def show
    @product = Product.find(params[:id])
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(params[:product])
    if @product.save
      redirect_to @product, :notice => "Successfully created product."
    else
      render :action => 'new'
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    if @product.update_attributes(params[:product])
      redirect_to @product, :notice  => "Successfully updated product."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to products_url, :notice => "Successfully destroyed product."
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_for @product do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :category_id %><br />
    <%= f.collection_select(:category_id, Category.all, :id, :name, :prompt => true) %>
  </p>
  <p>
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </p>
  <p>
    <%= f.label :released_at %><br />
    <%= f.date_select :released_at %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/products/_product.html.erb
<div class="product">
  <h2><%= link_to product.name, product %></h2>
  <div class="details">
    <%= number_to_currency(product.price) %>
    <% if product.category %>
      | Category: <%= product.category.name %>
    <% end %>
  </div>
</div>

app/views/products/edit.html.erb
<%= title "Edit Product" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @product %> |
  <%= link_to "View All", products_path %>
</p>

app/views/products/index.html.erb
<%= title "Products" %>

<%= form_tag products_path, method: :get do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= button_tag "Search", name: nil %>
  </p>
<% end %>

<p><%= link_to "Advanced Search", new_search_path %></p>

<div id="products">
  <%= render @products %>
</div>

app/views/products/new.html.erb
<%= title "New Product" %>

<%= render 'form' %>

<p><%= link_to "Back to List", products_path %></p>

app/views/products/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>
<p>
  <strong>Category:</strong>
  <%= @product.category_id %>
</p>
<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>
<p>
  <strong>Relased At:</strong>
  <%= @product.released_at %>
</p>

<p>
  <%= link_to "Edit", edit_product_path(@product) %> |
  <%= link_to "Destroy", @product, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", products_path %>
</p>